[package]
name = "privacy_lending_pool"
type = "bin"
authors = ["masaun"]
version = "0.0.1"

[dependencies]
binary_merkle_root = { git = "https://github.com/privacy-scaling-explorations/zk-kit.noir", tag = "binary-merkle-root-v0.0.1", directory = "packages/binary-merkle-root" }
poseidon = { tag = "v0.2.3", git = "https://github.com/noir-lang/poseidon" }
